version: '3.7'

services:
  mmaction2_automation:
    image: rlleshi/motionbank_mmaction2:automation
    #tty: true
    deploy:
      placement:
        constraints: [node.hostname == motionbank-compute-00]
    volumes:
      - data-transfer-auto:/data-transfer
    entrypoint: /bin/bash
    command: >
        -c "python3 demo/process_automation.py /data-transfer/read /data-transfer/write/ --format json --stride 0.15"
volumes:
  data-transfer-auto:
    driver: local
    name: data-transfer-auto
